version: 2.1

##
# Aliases
##

defaults: &defaults
  docker:
    - image: circleci/node:dubnium

##
# Jobs
##

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore node_modules cache
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          name: Cache node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run tests
          command: npm test

##
# Workflows
##

workflows:
  version: 2
  test:
    jobs:
      - install
      - test:
          requires:
            - install
